"""Configuration loaded from environment. Secrets come from Ansible Vault
via the profile.env file generated by the deploy role - never hardcoded,
never logged. Mirrors integration/erpnext-bridge/app/config.py so the two
bridges stay consistent for anyone reading both.
"""

import os
from dataclasses import dataclass, field


@dataclass
class ProfileConfig:
    name: str
    shared_secret: str


@dataclass
class Settings:
    onyx_base_url: str = os.environ.get("ONYX_BASE_URL", "http://169.58.107.168:3000")
    onyx_api_key: str = os.environ.get("ONYX_API_KEY", "")
    cc_pair_legal: int = int(os.environ.get("ONYX_CC_PAIR_LEGAL", "0"))
    cc_pair_project: int = int(os.environ.get("ONYX_CC_PAIR_PROJECT", "0"))
    rate_limit_per_minute: int = int(os.environ.get("BRIDGE_RATE_LIMIT_PER_MINUTE", "20"))
    request_timeout_seconds: float = float(os.environ.get("BRIDGE_REQUEST_TIMEOUT", "60"))
    audit_log_path: str = os.environ.get("BRIDGE_AUDIT_LOG", "/data/onyx-bridge/audit.log")
    profiles: dict = field(default_factory=dict)

    def cc_pair_for(self, target: str) -> int:
        if target == "legal":
            return self.cc_pair_legal
        if target == "project":
            return self.cc_pair_project
        raise ValueError(f"Unknown target: {target!r} (expected 'legal' or 'project')")

    def load_profiles(self):
        names = [n.strip() for n in os.environ.get("BRIDGE_PROFILE_NAMES", "").split(",") if n.strip()]
        for name in names:
            key = name.upper().replace("-", "_")
            self.profiles[name] = ProfileConfig(
                name=name,
                shared_secret=os.environ[f"PROFILE_{key}_SHARED_SECRET"],
            )
        return self


settings = Settings()
