"""Configuration loaded from environment. All secrets come from Ansible
Vault via the profile.env file generated by roles/erpnext-bridge — never
hardcoded, never logged.
"""

import os
from dataclasses import dataclass, field


@dataclass
class ProfileConfig:
    name: str
    shared_secret: str
    erpnext_api_key: str
    erpnext_api_secret: str
    role: str  # "ops-admin" | "staff-work" | "sales-crm"
    # The ERPNext User this profile authenticates as (e.g.
    # "hermes-ops@company.local") — needed for "_assign"-style filters
    # ("my tasks", "my leads"). Distinct from erpnext_api_key: the API key
    # is an opaque token, not the username ERPNext stores in the _assign
    # JSON list, so tools were filtering on the wrong value before this
    # field existed (confirmed: erp_list_my_tasks always returned empty
    # even right after creating and being assigned a task).
    erpnext_email: str = ""


@dataclass
class Settings:
    erpnext_base_url: str = os.environ.get("ERPNEXT_BASE_URL", "http://erpnext-frontend:8080")
    rate_limit_per_minute: int = int(os.environ.get("BRIDGE_RATE_LIMIT_PER_MINUTE", "60"))
    request_timeout_seconds: float = float(os.environ.get("BRIDGE_REQUEST_TIMEOUT", "10"))
    idempotency_db_path: str = os.environ.get("BRIDGE_IDEMPOTENCY_DB", "/data/idempotency.sqlite3")
    audit_log_path: str = os.environ.get("BRIDGE_AUDIT_LOG", "/data/audit.log")
    profiles: dict = field(default_factory=dict)

    def load_profiles(self):
        """Each Hermes profile gets its own shared secret + ERPNext API
        credentials, all injected as PROFILE_<NAME>_* env vars by the
        erpnext-bridge Ansible role. A profile can only ever act as the
        ERPNext user tied to its own API key — there is no "master" key.
        """
        names = [n.strip() for n in os.environ.get("BRIDGE_PROFILE_NAMES", "").split(",") if n.strip()]
        for name in names:
            key = name.upper().replace("-", "_")
            self.profiles[name] = ProfileConfig(
                name=name,
                shared_secret=os.environ[f"PROFILE_{key}_SHARED_SECRET"],
                erpnext_api_key=os.environ[f"PROFILE_{key}_API_KEY"],
                erpnext_api_secret=os.environ[f"PROFILE_{key}_API_SECRET"],
                role=os.environ.get(f"PROFILE_{key}_ROLE", name),
                erpnext_email=os.environ.get(f"PROFILE_{key}_EMAIL", ""),
            )
        return self


settings = Settings()
